### ISSUE TITLE
Add hcl files to gitignore

### ISSUE THREAD

**Issue by mike-wazowski007** [anthonyk-pack/TerraformAWSProject1#1]
Currently,

Need to add the HCL lock files to the .gitignore file to ignore hcl lock file

**Comment by anthonyk-pack** [comment]
Hey Mike - On what grounds should I add this to the git ignore please?

**Comment by mike-wazowski007** [comment]
Ahh you do not need to track it :) again your choice

**Comment by mike-wazowski007** [comment]
I raise a new one :)
